# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Liqiang He
tagline:          'Liqiang'
description:      'A Software Engineer/Photographer/Gastronome'
url:              https://helq2612.github.io/
baseurl:          https://helq2612.github.io/

author:
  name:           'Liqiang He'
  url:            https://helq2612.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/helq2612
